# Generated by Django 5.0.1 on 2024-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0002_category_alter_artwork_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Artapp/cimg'),
        ),
    ]
