# Generated by Django 5.0.1 on 2024-02-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0008_artwork_aimg_artwork_artworkstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='participants',
        ),
        migrations.CreateModel(
            name='BuyAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artapp.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artapp.buyer')),
            ],
        ),
    ]
