# Generated by Django 5.0.1 on 2024-03-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0009_remove_auction_participants_buyauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='frame',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('datePosted', models.DateTimeField()),
                ('reply', models.TextField()),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artapp.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artapp.user')),
            ],
        ),
    ]
