# Generated by Django 5.0.1 on 2024-03-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0010_artwork_condition_artwork_frame_artwork_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
