# Generated by Django 5.0.1 on 2024-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0011_alter_artwork_height_alter_artwork_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.BooleanField(default=True),
        ),
    ]
