# Generated by Django 5.0.1 on 2024-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0012_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
