# Generated by Django 5.0.1 on 2024-03-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0013_alter_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobileNo',
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(max_length=10),
        ),
    ]
