# Generated by Django 5.0.1 on 2024-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0016_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='verified',
        ),
        migrations.AlterField(
            model_name='seller',
            name='portfolio',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='successAuctions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='totalSales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
