# Generated by Django 5.0.1 on 2024-03-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0017_remove_seller_verified_alter_seller_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='favourites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artapp.artwork'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='totalBids',
            field=models.IntegerField(default=0),
        ),
    ]
