# Generated by Django 5.0.1 on 2024-03-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0019_remove_bid_bidtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artapp.buyer'),
        ),
    ]
