# Generated by Django 5.0.1 on 2024-04-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0021_remove_buyauction_auction_remove_buyauction_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
