# Generated by Django 5.0.1 on 2024-04-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0022_remove_seller_portfolio_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
